
const termsAndConditionsData = [
    {
        id: 1,
        details:
            'Feelshoot with its registered office at 2-191, Bhima Rao Nilayam, Ramalayam Street, MPUP School, Yendada, Rushikonda, APIIC, Visakhapatnam-530045, Andhra Pradesh and Corporate office at 3rd Floor, Flat No. 3, Plot No. 10, Shri Shirdi, Sai Veterinary Colony, Sri Padmavathi Nilayam, Vishalakshi Nagar, Visakhapatnam, Andhra Pradesh 530043 is the creator, owner and publisher of the MicroBird, including but not limited to the website titled https://usrrutechnologies.com/(hereinafter referred to as “Online Platform” or “Platform”). The Company owns and operates the services provided through its Online Platform, which may be modified, deleted, updated (temporarily or permanently) from time to time at the discretion of the Company.',
    },
    {
        id: 2,
        details:
            'These terms of use (“Terms”), including the various policies incorporated by reference in these Terms, govern your access to and use of this Application and the underlying services provided by us through the Application, including our SMS, APIs, email notifications, ads, commerce services, and our other covered services that may link to these Terms (collectively, the “Services”), and any information, text, graphics, photos or other materials uploaded, downloaded or appearing on or as a part of the Services (collectively referred to as “Content”). Your access to and use of the Services, however accessed, constitutes your agreement to be bound by these Terms, which establishes a contractual relationship between You and the Company. When You use any of the Services provided by Us through the Application, you will be subject to the rules, guidelines, policies, terms, and conditions applicable to such Service, and they shall be deemed to be incorporated into and shall apply in addition to these Terms. If you transact on our website, you shall be subject to the policies that are applicable for such transaction.',
    },
    {
        id: 3,
        details:
            'Please read the Terms and Conditions set out herein carefully and in their entirety. Please also acknowledge the Privacy Policy which may be separately set out on the Online Platform. The Privacy Policy shall constitute a part of these Terms and Conditions. Terms and Conditions together with the Privacy Policy is hereinafter collectively referred to as the Terms',
    },
    {
        id: 4,
        details:
          'If you do not agree to be bound by all the Terms set forth herein, you are not authorized to use or access the services of the Online Platform. These Terms constitute an agreement between MicroBird and you in connection with your use of the Online Platform, as defined below. If you have any questions regarding our services, you can email us at info@usrrutechnologies.com.',
    },
    {
        id: 5,
        details:
        'This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable. This electronic record is generated by a computer system and does not require any physical or digital signatures. This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and terms of use for access or usage of this Website (“Platform”).',
    },
    {
        id: 6,
        details:
        'We reserve the right, at our sole discretion, to change, modify, add or remove portions of these Terms, at any time without any prior written notice to you. It is your responsibility to review these Terms periodically for updates / changes. Your continued use of the website following the posting of changes will mean that you accept and agree to the revisions. As long as you comply with these terms, we grant you a personal, non-exclusive, non-transferable, limited privilege to access and use the services.',
    },
    {
        id: 7,
        details:
        'In the event a special feature with its own terms and conditions is offered, the same shall apply in addition to these terms. In case of a conflict of the terms and conditions of such special feature with these terms, the terms specific to the special feature shall prevail.',
    },
  ]

  const termsAndConditionsDetails = [
    {
      id: 1,
      section: '1.0 IN THESE TERMS, UNLESS THE CONTEXT OTHERWISE REQUIRES, REFERENCES TO:',
      details: [
        {
          id: 1,
          details: '1.12 “We”, “we”, “Us”, “us” or “MicroBird” shall mean USR&RU TECHNOLOGIES PRIVATE LIMITED, its affiliates, permitted assigns and partners, and the terms “Our” and “our” shall be construed accordingly; and',
        },
        {
          id: 2,
          details: '1.13 “You”, “you”, “User” or “user”, shall mean any natural or legal person who has agreed to become an end user by accessing the Contents of the website, or using the website or the Services offered through the website, by providing some personal information (more particularly described in the Privacy Policy and including but not limited to your name, address, mobile phone number and email while registering on the website (“Registration Data”), and the terms “Your” and “your” shall be construed accordingly.',
        },
      ],
    },
    {
      id: 2,
      section: '2.0 APPLICABILITY OF TERMS:',
      details: [
        {
          id: 1,
          details: '2.1 By accessing and/or using all or a portion of the Services, You acknowledge and agree that:',
        },
        {
          id: 2,
          details: '2.1.1 You have read and understood the Terms;',
        },
        {
          id: 3,
          details: '2.1.2 The provisions, disclosures and disclaimers set forth in the Terms are fair and reasonable;',
        },
        {
          id: 4,
          details: '2.1.3 Your agreement to follow and be bound by these terms and conditions is voluntary and not the result of fraud, duress or undue influence exercised upon You by any person or entity;',
        },
        {
          id: 5,
          details: '2.1.4 Written approval is not a prerequisite to the validity or enforceability of the Terms.',
        },
        {
          id: 6,
          details: '2.2 The Terms are governed by and comply with the provisions of applicable Indian law, including but not limited to:',
        },
        {
          id: 7,
          details: '2.2.1 The Indian Contract Act, 1872;',
        },
        {
          id: 8,
          details: '2.2.2 The (Indian) Information Technology Act, 2000;',
        },
        {
            id: 9,
            details: '2.2.3 Information Technology (Procedure and Safeguards for Interception, Monitoring and Decryption of Information) Rules, 2009;',
        },
        {
            id: 10,
            details: '2.2.4 Information Technology (Procedure and Safeguards for Monitoring and Collecting Traffic Data or Information) Rules 2009;',
        },
        {
            id: 11,
            details: '2.2.5 The rules, regulations, guidelines and clarifications framed there under, including the (Indian) Information Technology (Reasonable Security Practices and Procedures and Sensitive Personal Information) Rules, 2011 (the “SPI Rules”), and the (Indian) Information Technology (Intermediaries Guidelines) Rules, 2011 (the “IG Rules”);',
        },
        {
            id: 12,
            details: '2.2.6 The orders, rules, regulations, guidelines, notifications and clarifications issued by any legislative, regulatory or governmental authority at central, state or local level.',
        },
      ],
    },
    {
        id: 3,
        section: '3.0 MODIFICATION OF TERMS',
        details: [
          {
            id: 1,
            details: '3.1 The Services and the Terms may be amended or deleted from time to time, at the sole discretion of the Company. The Terms, including the Privacy Policy, will apply to your use of the Platform, as well as to all information provided by You on the Platform at any given point in time. The Company reserves the right to modify the Terms from time to time Such changes shall be notified on the Platform. You are advised to read the Terms regularly. You acknowledge and agree that it is your responsibility to review the Terms periodically to familiarize yourself with any modifications. Your continued use of the Online Platform following any such modification constitutes your agreement to follow and be bound by the Terms so modified.',
          },
          {
            id: 2,
            details: '3.2 If you do not agree to any changes in the Terms as they may occur, your continued right to access and use the Platform and/or the Services shall immediately terminate, and you agree that you shall discontinue your use of the Services. You agree that the Company is not liable to you or to any third party for any modification of the Terms or termination of your access to the Services except as specifically set forth herein.',
          },
          {
            id: 3,
            details: '3.3 These Terms allows the Company to access Registered Users’ contact information, including but not limited to email address and phone number for communication purposes so as to provide you with the Services and/or to obtain feedback, comments, suggestions, opinions, reviews in relation to your use of the Platform, the Services.',
          },
        ],
      },
      {
        id: 4,
        section: '4.0 CONDITIONS OF USE',
        details: [
          {
            id: 1,
            details: '4.1 You must be 18 years of age or older to access or avail the Services in any manner. By signing in to the Online Platform, accessing and/or using all or any part of the Services, you represent and warrant to the Company that you are 18 years of age or older, and that you have the legal right, authority and capacity to use all or part of the Services available through the Platform, and agree to and abide by the Terms.',
          },
          {
            id: 2,
            details: '4.2 Whilst the Services are not intended to be used by minors, the Company respects and recognizes the privacy of minors who may inadvertently use our Platform. It is strongly recommended that parents and guardians use parental control tools to help protect minors from any offences, harm or breach of privacy and supervise the use of the Platform by minors.',
          },
          {
            id: 3,
            details: '4.3 You must not create a Customer account unless you are at least 18 years of age. If you are a parent or legal guardian permitting a person who is at least 13 years of age but under 18 years of age (a Minor) create a Customer account and/or use the Site, you agree to: (i) supervise the Minor’s use of the Site and their account; (ii) assume all risks associated with, and liabilities resulting from, the Minor’s use of the Site and their Customer account; (iii) ensure that the content on the Site is suitable for the Minor; (iv) ensure all information submitted to us by the Minor is accurate; and (v) provide the consents, representations and warranties contained in the Terms on the Minor’s behalf.',
          },
          {
            id: 4,
            details: '4.4 The Services are provided to you only for your personal, non-commercial use. You shall not resell the products ordered from the Platform.',
          },
          {
            id: 5,
            details: '4.5 You understand and acknowledge that the Platform and its Services are to be accessed by you on your own behalf or for your own personal use only. You shall not register on the Platform or use its Services on behalf of any third party or entity, nor shall you allow a third party or entity to use the Platform and its Services on your behalf.',
          },
          {
            id: 6,
            details: '4.6 The Company offers you a non-transferable, non-exclusive, limited right to access the Platform, use the Services provided on this Platform, provided that you comply with the Terms as set out in full. You acknowledge and agree that any authority or permission granted to you by the Company to use and access the Services and the Platform, including but not limited to access links, SMS notifications, OTPs, email address, QR codes, shall be used and accessed by you only. You acknowledge that the Company shall not be liable for any loss, cost, expense or damage incurred by you as a result of you accessing the platform and utilizing its services via access links, SMS notifications, OTPs, email address, QR codes etc. which have not been delivered to you personally by the Company.',
          },
          {
            id: 7,
            details: "4.7 You agree that the access you have been granted prohibits you from using the Services for any illegal or unauthorized purpose. You will make every reasonable effort to prevent unauthorized third parties from accessing the Platform and the Services. You will make every reasonable effort to protect your device and account from a security breach, including but not limited to hacking, phishing etc. You represent and warrant that you will not breach the security of the Platform or its Software or attempt to gain unauthorized access to or interfere with any other person's use of the Services.",
          },
          {
            id: 8,
            details: '4.8 For the purpose of the Terms, "Software" means (i) the server, platform and application software hosted by or on behalf of the Company, underlying and used to deliver the Services, (ii) all server, platform and application software of third parties used to host, support or connect the software referred to in subsection (i) and accessible by you as part of the Services, and (iii) all underlying algorithms, user interfaces and network and database designs and schemas, architecture, class libraries and objects, the unique expressions of the selection, organization and presentation of user-visible functions, all updates, upgrades, patches, maintenance releases and bug fixes and all documentation relating to any of the foregoing.',
          },
        ],
      },
      {
        id: 5,
        section: '5.0 REGISTRATION',
        details: [
          {
            id: 1,
            details: '5.1 To fully avail the Services of the Website, registration is required. You are required to create a profile for Yourself by providing the following information which inter alia includes Name, Phone No, Email ID, Location, Gallery, Phonebook, Date of birth, Interest and Preferred language. Users who register with us can purchase the listed Products and avail the Services of the Website. The Website offers the Users an option of signing up through other third-party social networking sites, including but not limited to Gmail, etc. Upon such signup, our servers gain access to information about You from Your social networking account, including but not limited to Your profile, date of birth, name and gender, and all such information is stored in Our system. Users who do not want to register with Us can check out as a guest and purchase the Products.',
          },
          {
            id: 2,
            details: '5.2 Information collected about you is subject to our Privacy Policy, which is incorporated in these Terms of Use by reference. Further, at any time during Your use of this Website, including but not limited to the time of registration, You are solely responsible for protecting the confidentiality of Your username and password, and any activity under the account shall be deemed to have been done by You. In the case that You provide Us with false and/or inaccurate details or We have reason to believe You have done so, We hold the right to permanently suspend Your account.',
          },
          {
            id: 3,
            details: '5.3 By using this Website and providing your contact information to us through the Website, you hereby agree and consent to receiving calls, autodialled and/or pre-recorded message calls, e-mails and SMSs from us and/or any of its affiliates or partners at any time, subject to the Policy. In the event that you wish to stop receiving any such marketing or promotional calls / email messages / text messages, you may send an e-mail to the effect tov [email]. You agree and acknowledge that it may take up to seven (7) business days for us to give effect to such a request by the you.',
          },
        ],
      },
      {
        id: 6,
        section: '6.0 LIMITED USE',
        details: [
          {
            id: 1,
            details: '6.1 The User agrees and undertakes not to reverse engineer, modify, copy, distribute, transmit, display, perform, reproduce, publish, license, create derivative works from, transfer, or sell any information or software obtained through the Platform. For the removal of any doubt, it is clarified that unlimited or complete reproduction, copying of the content for commercial or non-commercial purposes and unwarranted modification of data and information within the content of the website is not permitted.',
          },
          {
            id: 2,
            details: '6.2 Throughout these Terms, MicroBird prior written consent means a communication issued by our legal department, specifically in response to Your request, and specifically addressing the activity or conduct for which You seek authorization.',
          },
        ],
      },
      {
        id: 7,
        section: '7.0 MICROBIRD REWARD POINTS',
        details: [
          {
            id: 1,
            details: '7.1 MicroBird Reward Points ("Reward Points") may be acquired through various methods as specified in the MicroBird Reward Points program ("Program"). These methods will be disclosed and detailed on our application.',
          },
          {
            id: 2,
            details: '7.2 The acquisition of Reward Points may be subject to specific terms, conditions, and eligibility criteria as outlined in the Program. Users are encouraged to review the Program to understand how Reward Points can be obtained.',
          },
          {
            id: 3,
            details: '7.3 Reward Points can be redeemed and utilized in accordance with the terms and conditions specified in the Program. Such redemptions may include, but are not limited to, obtaining discounts, accessing exclusive offers, or receiving other benefits related to products or services offered on the Platform.',
          },
          {
            id: 4,
            details: '7.4 It is important to note that Reward Points hold can be converted into currency or any other form of legal tender only with the discretion of the Company subject to proper KYC verification and approval of designated bank account. ',
          },
          {
            id: 5,
            details: '7.5 Reward Points are exclusively intended for use on the MicroBird platform and in conjunction with the services provided, unless explicitly stated otherwise within the Program.',
          },
          {
            id: 6,
            details: '7.6 Reward Points are non-transferable and non-assignable, except in cases where MicroBird expressly permits such transfers or assignments in writing. Users may not sell, barter, or otherwise dispose of Reward Points to other users or third parties unless specifically authorized by MicroBird.',
          },
          {
            id: 7,
            details: "7.7 Any unused Reward Points may automatically expire upon the termination of the user's account or as stated in the Program's terms and conditions.",
          },
          {
            id: 8,
            details: "7.8 Users are advised that violations of MicroBird's policies or misuse of Reward Points may result in account termination and forfeiture of Reward Points.",
          },
          {
            id: 9,
            details: '7.9 MicroBird reserves the right to manage, regulate, control, modify, or discontinue the Reward Points program at its sole discretion and without prior notice. Such management may occur for reasons including, but not limited to, policy violations, legal requirements, or technical considerations.',
          },
          {
            id: 10,
            details: '7.10 Eligibility for Withdrawal',
          },
          {
            id: 11,
            details: "7.10.1 Users must have accumulated a minimum number of Reward Points as specified in the Program's terms and conditions.",
          },
          {
            id: 12,
            details: '7.10.2 Users must maintain a valid and active user account on the Website.',
          },
          {
            id: 13,
            details: '7.10.3 Users must adhere to all terms and conditions outlined in this Policy and the Program.',
          },
          {
            id: 14,
            details: '7.10.4 Users must have provided accurate and complete account information, including but not limited to banking details and UPI (Unified Payments Interface) IDs.',
          },
          {
            id: 15,
            details: "7.11 Withdrawal Process",
          },
          {
            id: 16,
            details: '7.11.1 Eligible users can initiate the withdrawal process by accessing the designated withdrawal section on the Website. The applicable daily withdrawal limits will be specified on the Website.',
          },
          {
            id: 17,
            details: '7.11.2 Users will be required to select the amount of Reward Points they wish to withdraw, subject to the minimum and maximum withdrawal limits specified in the Program.',
          },
          {
            id: 18,
            details: "7.11.3 Users must verify the accuracy of their banking information, including but not limited to the nominated bank account or UPI ID. It is the user's responsibility to ensure that all provided account information is correct and matches the user's identity.7.11.1 Eligible users can initiate the withdrawal process by accessing the designated withdrawal section on the Website. The applicable daily withdrawal limits will be specified on the Website.",
          },
          {
            id: 19,
            details: '7.11.4 Upon successful submission of the withdrawal request, users will receive a confirmation notification. The rate of withdrawal, denominated in Indian National Rupee, will be displayed at the point of withdrawal.',
          },
          {
            id: 20,
            details: "7.11.5 The applicable cash payment will be directly credited to the user's nominated bank account or UPI ID, as specified in their withdrawal request.",
          },
          {
            id: 21,
            details: "7.12 The Platform reserves the right to verify the user's identity, age, and eligibility qualifications to its satisfaction before processing any payment. Users may be required to provide additional documentation, including but not limited to a photocopy of their state ID card or other proof as deemed necessary by the Platform.",
          },
          {
            id: 22,
            details: "7.13 Payment will not be processed to a designated bank account or UPI ID with an email address, first name, and last name that differs from the information on the user's account, or an account that has not been verified.",
          },
          {
            id: 23,
            details: "7.14 While the Platform endeavors to fulfill all withdrawal requests in a timely manner, users acknowledge and agree that the Platform does not guarantee the fulfillment of withdrawal requests within a specific period. Estimated timings provided at the time of withdrawal are for reference purposes only, and the Platform shall not be liable for any delays in processing withdrawals.",
          },
          {
            id: 24,
            details: '7.15 Users are responsible for any taxes imposed under applicable laws on the payments received through the withdrawal of Reward Points, including any related penalties or interest. The Platform reserves the right to deduct applicable taxes before making payments if required by applicable law',
          },
          {
            id: 25,
            details: '7.16 The Platform reserves the right to manage, regulate, control, modify, or eliminate the withdrawal feature, in part or in whole, where it has a valid reason to do so. Valid reasons may include, but are not limited to, instances where the user has violated this Policy, breached any applicable law or regulation, or for legal, security, or technical reasons. Users agree that the Platform shall have no liability based on its exercise of such right.',
          },
        ],
      },
      {
        id: 8,
        section: '8.0 TERMINATION',
        details: [
          {
            id: 1,
            details: "8.1 Termination by User: You have the option to terminate this Agreement at any time by deleting your Account and discontinuing all usage of the Platform. Please be aware that removing the Platform from your device will not automatically delete your Account. To delete your Account, log in to your Account on the Site or click the Account profile icon in the App, and within your Account profile, select 'Delete Account.' Deleting your Account will result in the automatic deletion of all User Content associated with it. Moreover, if you wish to remove specific User Content you've uploaded to the Platform, you can use the User Content deletion features within the Platform. However, please note that deleting User Content will not delete your Account or terminate this Agreement. This Agreement, including any posted revisions, will remain in full effect as long as you use the Platform, with certain provisions continuing to apply even after termination.",
          },
          {
            id: 2,
            details: '8.2 Termination by MicroBird: MicroBird reserves the right to disable or terminate your user account, remove or disable any content you upload or share, at any time. This includes cases where you have failed to comply with any of the provisions of these Terms, or if activities on your account are deemed by MicroBird, in its sole discretion, to potentially cause harm to or impair the Services, infringe upon or violate third-party rights, or contravene any applicable laws or regulations. Following such termination or suspension, you are prohibited from accessing or using the Platform. You also agree not to attempt re-registration under a different member name or by any other means.',
          },
          {
            id: 3,
            details: '8.3 Platform may entail the removal of access and the prevention of further use of the Platform. Termination also includes the disassociation of your username, password, and all associated information, files, and user content within your account. On termination, all your profile content and other information may be deleted. Nonetheless, certain details are retained by us for archival and legal purposes. Regardless of termination, content liability remains with the User at all times. Upon termination, your right to use the Platform, including mobile software, will cease automatically. MicroBird assumes no liability to you for any suspension or termination, including the deletion of your user content. MicroBird will retain and utilize content/data for as long as required and/or permissible under local laws. All provisions of this Agreement that, by their nature, should survive, will indeed survive termination, including but not limited to warranty disclaimers, governing law, and limitations of liability.',
          },
        ],
      },
      {
        id: 9,
        section: '9.0 YOUR OBLIGATIONS',
        details: [
          {
            id: 1,
            details: "9.1 You agree and undertake that you are accessing the Application and transacting at your sole risk and are that you are using your best and prudent judgment before using the Application or accessing/using any information displayed thereon.",
          },
          {
            id: 2,
            details: '9.2 You agree that they are solely responsible to us and to any third party for any breach of Your obligations under the Terms of Use and for the consequences including any loss or damage which we or our affiliates may suffer for any such breach.',
          },
          {
            id: 3,
            details: '9.3 You agree that we may, at any time, modify or discontinue all or part of the Website, charge, modify or waive fees required to use the Website, or offer opportunities to some or all Website Users.',
          },
          {
            id: 4,
            details: '9.4 You agree to provide correct and accurate credit/ debit card details to the approved payment gateway for availing Services on the Website. You shall not use the credit/debit card, which is not lawfully owned by You, i.e. in any transaction, You must use Your own credit/ debit card.',
          },
        ],
      },
      {
        id: 10,
        section: '10.0 REVIEWS, FEEDBACK AND DATA RETENTION',
        details: [
          {
            id: 1,
            details: "10.1 You may be invited by the Company to submit feedback, ratings, suggestions, comments, opinions or reviews on the Platform. It is up to your discretion for to submit the same.",
          },
          {
            id: 2,
            details: '10.2 You are solely responsible for the information and content that you choose to submit to the Company on the Platform, including but not limited to the feedback, ratings, suggestions, comments, opinions or reviews relating to Products purchased by you. You agree not to post or publish any content on the Online Platform that amounts to:',
          },
          {
            id: 3,
            details: '10.2.1 An infringement of any Company or third-party intellectual property or privacy rights.',
          },
          {
            id: 4,
            details: '10.2.2 A violation of applicable laws or regulations, including but not limited to the relevant rules under Information technology Act, 2000.',
          },
          {
            id: 5,
            details: "10.2.3 Defamation.",
          },
          {
            id: 6,
            details: '10.3 The Company may choose, in its sole discretion, to use, analyze, and/or publish your reviews, ratings, opinion, comments and feedback in accordance with these Terms. You agree to be contacted by the Company via telephonic or electronic communication for the purposes of obtaining feedback in relation to the Products purchased, dispute resolution, complaint resolution, any further information. The information or content provided by you may be used by the Company for business purposes, including but not limited to market research, consumer behaviors and profiling, data analytics, tracking market trends on an anonymized basis.',
          },
          {
            id: 7,
            details: '10.4 The Company is deemed to be a mere “intermediary” as defined under the applicable laws with respect to publishing of any information and content on the Platform and disclaims all responsibility and liability with respect to publishing of your information and content. The Company is not liable to pay any consideration to you for republishing or repeatedly publishing any information or content provided by you on Platform.',
          },
          {
            id: 8,
            details: '10.5 The Company may retain such information and content provide by you on the Platform for as long as necessary, depending on the type of information; purpose, means and modes of usage of such information; and according to the Sensitive Personal Information Rules.',
          },
          {
            id: 9,
            details: '10.6 We have no obligation to monitor the materials posted on the Website. We shall have the right to remove or edit any content that in its sole discretion violates, or is alleged to violate, any applicable law or either the spirit or letter of these Terms of Service. Notwithstanding this right, YOU REMAIN SOLELY RESPONSIBLE FOR THE CONTENT OF THE MATERIALS YOU POST ON THE WEBSITE AND IN YOUR PRIVATE MESSAGES. In no event shall We assume or have any responsibility or liability for any Content posted or for any claims, damages or losses resulting from the use of Content and/or appearance of Content on the Website. You hereby represent and warrant that You have all necessary rights in and to all Content Which You provide and all information it contains and that such Content shall not infringe any proprietary or other rights of third parties or contain any libelous, tortuous, or otherwise unlawful information.',
          },
        ],
      },
      {
        id: 11,
        section: '11.0 INTELLECTUAL PROPERTY RIGHTS',
        details: [
          {
            id: 1,
            details: "11.1 The Services and all processes, content including but not limited to any feedback, ratings, suggestions, comments or reviews relating to the products or use of Services provided by the Company, software, market data, research and analyses, consumer insights, and methodologies, anonymized consumer profiling data, know-how, packaging, appearance, style, designs, and trade secrets used by the Company in creating and performing the Services and operating the Platform as well as any related Intellectual Property rights throughout the world and all modifications thereto and derivative works thereof developed solely by the Company, or by or with the input of another party (the 'Company Intellectual Property') are protected by Indian copyright laws and other intellectual property laws. They belong exclusively to the Company and may not be used or reproduced by you without the express written permission of the Company.",
          },
          {
            id: 2,
            details: '11.2 The Company hereby reserves any and all rights in the Company Intellectual Property. You agree that, you will not: (a) alter, modify, adapt, reverse engineer, decompile, disassemble the products or services or hack the software, or create derivative works from the Company Intellectual Property; (b) license, share, resell, sell, or otherwise transfer the Company Intellectual Property or access to such Company Intellectual Property to any third party; (c) reverse engineer, decompile, disassemble, or otherwise attempt to derive the source code for the Company Intellectual Property; (d) remove or alter any copyright or trademark notices or other notices included in the Company Intellectual Property;',
          },
        ],
      },
      {
        id: 12,
        section: '12.0 LIMITATION OF LIABILITY',
        details: [
          {
            id: 1,
            details: "Please read this section carefully as it limits the liability of MicroBird and its parents, subsidiaries, affiliates, related companies, officers, directors, employees, agents, representatives, partners, and licensors (collectively, the MicroBird) Each of the subsections below only applies up to the maximum extent permitted under applicable law. Nothing in this section is intended to limit any rights you may have which may not be lawfully limited.",
          },
          {
            id: 2,
            details: '12.1 Your access to and use of the Services or any Content are at your own risk. You understand and agree that the Services are provided to you on an “AS IS” and “AS AVAILABLE” basis without any representation or warranties, express or implied except otherwise specified in writing. Without limiting the foregoing, to the maximum extent permitted under applicable law, WE DISCLAIM ALL WARRANTIES AND CONDITIONS, WHETHER EXPRESS OR IMPLIED, OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT.',
          },
          {
            id: 3,
            details: '12.2 Without prejudice to the foregoing, We make no warranty or representation and disclaim all responsibility and liability for: (i) the completeness, accuracy, availability, timeliness, security or reliability of the Services or any Content; (ii) any harm to your computer system, loss of data, or other harm that results from your access to or use of the Services or any Content; (iii) the deletion of, or the failure to store or to transmit, any Content and other communications maintained by the Services; and (iv) whether the Services will meet your requirements or be available on an uninterrupted, secure, or error-free basis. No advice or information, whether oral or written, obtained from us or through the Services, will create any warranty or representation not expressly made herein.',
          },
          {
            id: 4,
            details: '12.3 TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, WE SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUES, WHETHER INCURRED DIRECTLY OR INDIRECTLY, OR ANY LOSS OF DATA, USE, GOOD-WILL, OR OTHER INTANGIBLE LOSSES, RESULTING FROM (i) YOUR ACCESS TO OR USE OF OR INABILITY TO ACCESS OR USE THE SERVICES; (ii) ANY CONDUCT OR CONTENT OF ANY THIRD PARTY ON THE SERVICES, INCLUDING WITHOUT LIMITATION, ANY DEFAMATORY, OFFENSIVE OR ILLEGAL CONDUCT OF OTHER USERS OR THIRD PARTIES; (iii) ANY CONTENT OBTAINED FROM THE SERVICES; OR (iv) UNAUTHORISED ACCESS, USE OR ALTERATION OF YOUR TRANSMISSIONS OR CONTENT.',
          },
          {
            id: 5,
            details: "12.4 IN NO EVENT SHALL THE AGGREGATE LIABILITY OF MICROBIRD EXCEED THE AMOUNT YOU PAID TO US, FOR THE SERVICES GIVING RISE TO THE CLAIM.",
          },
          {
            id: 6,
            details: '12.5 THE LIMITATIONS OF THIS SUBSECTION SHALL APPLY TO ANY THEORY OF LIABILITY, WHETHER BASED ON WARRANTY, CONTRACT, STATUTE, TORT (INCLUDING NEGLIGENCE) OR OTHERWISE, AND WHETHER OR NOT WE HAVE BEEN INFORMED OF THE POSSIBILITY OF ANY SUCH DAMAGE, AND EVEN IF A REMEDY SET FORTH HEREIN IS FOUND TO HAVE FAILED OF ITS ESSENTIAL PURPOSE.',
          },
        ],
      },
      {
        id: 13,
        section: '13.0 INDEMNIFICATION',
        details: [
          {
            id: 1,
            details: "13.1 You agree to indemnify and hold harmless the Company and its officers, directors, employees and agents from any charges, complaints, damages, losses, liabilities, costs and expenses (including attorneys' fees and expert fees) due to, arising out of or relating in any way to any violation by you of the Terms, including but not limited to obligations stated therein relating to representation, warranty, intellectual property, access by minors, any applicable rule, regulation or law, your access or use of the Services and the Platform.",
          },
        ],
      },
      {
        id: 14,
        section: '14.0 FORCE MAJEURE',
        details: [
          {
            id: 1,
            details: "14.1 The Company will not be responsible for a breach of the Terms, damages, losses, costs or expenses, caused by any failure or delay of performance of Services and disruption to the Platform if such failure or delay is caused by an act of war, floods, fires, inclement weather conditions, hostility, or sabotage, an act of God, pandemics, lockdowns, Labour stoppages, an electrical, internet, cellular network or telecommunication failure or power outage, government restrictions, political strikes or another event outside the reasonable control of the Company.",
          },
        ],
      },
      {
        id: 15,
        section: '15.0 INVALIDITY',
        details: [
          {
            id: 1,
            details: "15.1 If any provision of the Terms is held to be invalid or unenforceable in whole or in part in any jurisdiction, then that provision shall be deemed ineffective in such jurisdiction but shall have no effect on the enforceability of the remaining provisions.",
          },
        ],
      },
      {
        id: 16,
        section: '16.0 SEVERABILITY',
        details: [
          {
            id: 1,
            details: "16.1 In the event any provision of the Terms become void or unenforceable, it shall not affect the validity of these Terms as a whole, and the unenforceable provisions shall be severed and the remainder of the provisions of these Terms shall continue in full force and effect.",
          },
        ],
      },
      {
        id: 17,
        section: '17.0 GOVERNING LAW AND JURISDICTION',
        details: [
          {
            id: 1,
            details: "17.1 For the purposes of the Terms:",
          },
          {
            id: 2,
            details: '17.1.1 (a) the term "Dispute" will mean any dispute, difference or claim arising out of or relating to: (i) the Terms, its interpretation, or the breach, termination, applicability or validity of the Terms; or (ii) any other dispute arising out of or relating to the relationship between the Company and you;',
          },
          {
            id: 3,
            details: '17.1.2 (b) the term “the Company Group" will mean the Company , its parents, subsidiaries, affiliates, stockholders, directors, officers, employees, agents, beneficiaries, assignees, successors in interest, and any third party which provides products or services purchased from or distributed by the Company ; and',
          },
          {
            id: 4,
            details: '17.1.3 (c) the term "User Group" will mean you and those in privity with you, your representatives, affiliates and family members.',
          },
          {
            id: 5,
            details: "17.2 These Terms shall be governed and interpreted by and construed in accordance with the substantive [Governing Law] and subject to arbitration provisions below, each party hereby irrevocably and finally submits to the exclusive jurisdiction of the courts of Visakhapatnam, Andhra Pradesh, India thereto in respect of any disputes, legal action or proceedings arising out of or in connection with the Terms, interpretation, duties, performance, breach, etc. of these Terms.",
          },
          {
            id: 6,
            details: '17.3 Should any Dispute arise out of or in connection with these Terms, the Parties hereto shall first endeavor to settle such Dispute amicably. If the Dispute is not resolved through amicable settlement within fifteen (15) days after commencement of discussions or such longer period as the Parties mutually agree in writing, then either Party may refer the Dispute for resolution by arbitration according to the provisions of the Arbitration and Conciliation Act, 1996 (India) or any statutory amendment or re-enactment thereof, or any statute enacted to replace the same, for the time being in force. The arbitration shall be conducted by a sole arbitrator appointed by mutual consent of the parties. The seat and venue of arbitration shall be in Visakhapatnam, Andhra Pradesh, India, and the language of the proceedings shall be English.',
          },
          {
            id: 7,
            details: '17.4 The Award rendered in any arbitration commenced hereunder shall be final and conclusive, and judgment thereon may be entered in any court having jurisdiction for its enforcement. The Parties undertake to implement the arbitration award. In addition, the Parties agree that no Party shall have any right to commence or maintain a suit or legal proceeding concerning a Dispute hereunder (other than for preventive or interlocutory relief pending completion of the arbitration proceedings under these Terms) until the Dispute has been determined in accordance with the arbitration procedure provided for herein and then only for the enforcement of the award rendered in such arbitration. When any Dispute is under arbitration, except for the matters under dispute, the Parties shall continue to exercise their remaining respective rights and fulfil their remaining respective obligations under these Terms.',
          },
        ],
      },
      {
        id: 18,
        section: '18.0 GENERAL',
        details: [
          {
            id: 1,
            details: "18.1 The Company's failure to exercise or enforce any right or provision of the Terms shall not be deemed to be a waiver of such right or provision. The Company is excused for any failure to perform to the extent that its performance is prevented by any reason outside of its control.",
          },
          {
            id: 2,
            details: '18.2 The Terms contain the entire agreement between the you and the Company and supersedes all prior agreements between the Parties regarding the subject matter contained herein, except as otherwise specifically noted herein.',
          },
          {
            id: 3,
            details: "18.3 In no event shall you seek or be entitled to rescission, injunctive or other equitable relief, or to enjoin or restrain the operation of the Services or use of the Platform.",
          },
          {
            id: 2,
            details: '18.4 You may not assign or delegate any rights or obligations under the Terms. Any purported assignment and delegation shall be ineffective. The Company may freely assign or delegate all rights and obligations under the Terms, fully or partially, without notice to you.',
          },
        ],
      },
  ];
  
  const TermsAndConditions = () => {
    return (
      <div className="container font-general-medium text-primary-dark dark:text-primary-light">
        <div className="text-center  text-left text-2xl font-bold  mt-14 sm:mt-20 mb-7">
          <h1>Terms & Conditons</h1>
        </div>
        <p className='mb-5'>Last Updated :- 28th October 2023</p>
        {termsAndConditionsData.map((details) => {
          return (				
            <p className="font-general-regular" key={details.id}>{details.details}</p> 
        )})}
        {termsAndConditionsDetails.map((section) => (
                <section className='mt-5' key={section.id}>
                <strong>{section.section}</strong>
                {section.details.map((detail) => (
                    <p className="font-general-regular mb-5" key={detail.id}>{detail.details}</p>
                ))}
                </section>
        ))}
      </div>
    );
  };
  
  export default TermsAndConditions;
  